version: "3.4"
services:
  peeringdb:
    image: docker.artifactory.globoi.com/peeringdb:v1.16
    platform: linux/amd64
    user: "0:0"
    build:
      context: ../..
      dockerfile: Dockerfile
      # target: tester
    container_name: peeringdb
    command: runserver 0.0.0.0:8888
    env_file: .env
    ports:
      # this needs to be set in the shell, compose env vars aren't read yet
      - "8888:8888"